name: Alerta de Vacantes LinkedIn

on:
  schedule:
    # Se ejecuta todos los días a las 13:00 UTC (07:00 AM CST - México)
    - cron: '0 13 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  extraer_y_enviar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install python-jobspy pandas

      - name: Ejecutar script de extracción
        run: python scraper.py

      - name: Enviar correo con resultados
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Nuevas Vacantes de LinkedIn extraídas
          to: matheisfn@gmail.com
          from: GitHub Actions
          body: El proceso automatizado finalizó. Adjunto encontrarás las vacantes de las últimas 24 horas.
          attachments: vacantes.csv
